# Generated by Django 3.0.5 on 2020-04-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_auto_20200414_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='insert_timestamp',
            new_name='inserted_timestamp',
        ),
    ]
